### ISSUE TITLE
feature: Docker for Mac support

### ISSUE THREAD

**Issue by renepardon** [ehough/docker-nfs-server#26]
Hello,
I try to run this docker conainer with the following docker-compose.yml file:

```yaml
version: '3'

services:
  nfs-server:
    image: erichough/nfs-server
    volumes:
      - nfs:/filesystem
      - ./nfs/exports.txt:/etc/exports:ro
    ports:
      - 20490:2049
    #    privileged: true
    cap_add:
      - CAP_SYS_ADMIN

volumes:
  nfs:
```

My OS: macOS Mojave (10.14.5 (18F132))
docker-compose version 1.24.0, build 0aa59064
docker-py version: 3.7.2
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

Client: Docker Engine - Community
 Version:           19.03.0-rc2
 API version:       1.40
 Go version:        go1.12.5

I receive the following error:

```
Attaching to dev-setup_nfs-server_1
nfs-server_1  | 
nfs-server_1  | ==================================================================
nfs-server_1  |       SETTING UP ...
nfs-server_1  | ==================================================================
nfs-server_1  | ----> kernel module nfs is missing
nfs-server_1  | ----> 
nfs-server_1  | ----> ERROR: nfs module is not loaded in the Docker host's kernel (try: modprobe nfs)
nfs-server_1  | ----> 
dev-setup_nfs-server_1 exited with code 1
```

How can I get this to work? :)
