### ISSUE TITLE
Problem running on ext4+overlay2 docker data directory

### ISSUE THREAD

**Issue by andyneff** [ehough/docker-nfs-server#37]
I've run into a strange problem with this docker, and I've yet to figure out what is going on. For some strange reason I can no longer successfully use this docker (when I could several kernels ago. I'm still using the same docker-compose I had ~ a year and a half ago). 

I'm out of ideas, I cannot figure out how the same image (the SHAs match) can work with one docker data directory and not the other. What am I missing to make this container work?

# Observations

## Not working

When I run it in my normal docker data folder I get:

Using `/var/lib/docker`:

```
# docker-compose down
Removing nfs_nfs_1 ... done
Removing network nfs_default
# docker-compose up
... (everything starts up the same)
# ls /mnt/data

# mount -vvv XservernameX:/nfs /mnt/data
mount.nfs: timeout set for Mon Feb 10 12:30:58 2020
mount.nfs: trying text-based options 'vers=4.2,addr=10.XX.XX.59,clientaddr=10.XX.XX.59'
mount.nfs: mount(2): No such file or directory
mount.nfs: trying text-based options 'addr=10.XX.XX.59'
mount.nfs: prog 100003, trying vers=3, prot=6
mount.nfs: portmap query retrying: RPC: Program not registered
mount.nfs: prog 100003, trying vers=3, prot=17
mount.nfs: portmap query failed: RPC: Program not registered
mount.nfs: mounting XservernameX:/nfs failed, reason given by server: No such file or directory
```

# Clean docker dir Working

However, I accidentally discovered that if I change the docker data dir, and restart the daemon, it works all of a sudden 😮 

Using `/var/lib/docker2`

```
# docker-compose down
Removing nfs_nfs_1 ... done
Removing network nfs_default
# docker-compose up
... (everything starts up the same)
# ls /mnt/data

# mount -vvv XservernameX:/nfs /mnt/data
mount.nfs: timeout set for Mon Feb 10 12:24:51 2020
mount.nfs: trying text-based options 'vers=4.2,addr=10.XX.XX.59,clientaddr=10.XX.XX.59'
# ls /mnt/data
foobar
# umount -vvv /mnt/data
/mnt/data: nfs4 mount point detected
/mnt/data: umounted
```

---

Here is the `docker-compose` file I'm using

```
version: '2.3'
services:
  nfs:
    image: erichough/nfs-server
    ports:
      - '2049:2049'
    cap_add:
      - SYS_ADMIN
      - SYS_MODULE
    volumes:
      - type: bind
        source: /opt/nfs_test
        target: /nfs
        read_only: false
      - type: bind
        source: /lib/modules
        target: /lib/modules
        read_only: true
    environment:
      - NFS_EXPORT_0=/nfs *(rw,insecure,no_subtree_check,fsid=1,no_root_squash,async)
      - NFS_DISABLE_VERSION_3=1
```

## Other things I tried that did not work

- `docker run -p 2049:2049 --cap-add SYS_ADMIN --cap-add SYS_MODULE -v /opt/nfs_test:/nfs:rw -v /lib/modules:/lib/modules:ro -e NFS_EXPORT_0='/nfs *(rw,insecure,no_subtree_check,fsid=1,no_root_squash,async)' -e NFS_DISABLE_VERSION_3=1 erichough/nfs-server`
- `--privileged`
- Pulled latest `erichough/nfs-server` image
- Removed docker "network", which the `docker` version of the command didn't even use.
- `network=host` and `127.0.0.1`
- Tried not setting `NFS_DISABLE_VERSION_3`, but that doesn't really work because `systemd` uses port 111, so that messes up `rpc-statd`

## A workaround

Now this is surprising, but I discovered that I could:

1. Start the nfs container with `/var/lib/docker2`
1. Mount `/mnt/data`. Success
1. Leave the dir mounted, and stop the docker
1. Switch the docker daemon back to `/var/lib/docker`
1. Start the nfs container with `/var/lib/docker`
1. `ls /mnt/data` works using the `/var/lib/docker` now.

This is not a great work around, but it seems to me to present even more questions than answers. 

## Other notes

- Running kernel: 5.4.13-201.fc31.x86_64
- I noticed I can no longer use the auto load nfsd trick in the docker, if I do, it perma hangs, and I have eventually reboot my machine and `modprobe` on the host before running the container. I suspect that this is due to me having a newer kernel, but have not tested this yet. I'm beginning to wonder that the kernel the image is built with is too different from my kernel to run `modprobe` command.
