### ISSUE TITLE
rpc.nfsd hangs on container start up

### ISSUE THREAD

**Issue by DeathRabbit679** [ehough/docker-nfs-server#43]
I'll preface this with saying this is probably a bug against me not knowing nfs things. I'm using the following compose file to spin the container.

```
version: "3.7"
services:
  nfs-server:
    container_name: nfs-server
    image: erichough/nfs-server:latest
    ports:
      - "2049:2049"
    volumes:
      - type: bind
        source: /mnt/nfstest
        target: /shares/nfstest

      - type: bind
        source: /home/cubeadmin/nfs/nfstest-exports-docker
        target: /etc/exports
        read_only: true
    environment:
      - NFS_DISABLE_VERSION_3=YES
      - NFS_LOG_LEVEL=DEBUG
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor=erichough-nfs
```
Exports file looks like this:
```
/shares/nfstest 192.168.1.0/24(fsid=0,rw,no_root_squash,no_subtree_check)
```
I am able to basically docker-compose restart down/up just fine until I mount the share from another system. After I do that, regardless of whether or not I unmount from the other system, the next time I try to restart the container, it hangs on `starting rpc.nfsd on port 2049 with 4 server thread(s)` . I'm unable to stop the container or even kill -9 the rpc.nfsd process at that point. It must be some sort of low level deadlock, but my brain has been too small to find the root cause thus far. :100:
