### ISSUE TITLE
example of docker-compose.yml

### ISSUE THREAD

**Issue by garanews** [ehough/docker-nfs-server#60]
Can some one please provide a sample of docker-compose with couple of services where docker-nfs-server is configured and used?

**Comment by sergiobrr** [comment]
I'm using this

```
nfs:
    image: erichough/nfs-server:latest
    volumes:
      - ./app/auto_tagging/models:/mnt/autotagging_models
      - ./exports:/etc/exports
    ports:
      - 2049:2049
      - 2049:2049/udp
      - 32765:32765
      - 32765:32765/udp
      - 32767:32767
      - 32767:32767/udp
    cap_add:
      -  SYS_ADMIN
     privileged: true
```
