### ISSUE TITLE
Error while mounting nfs in a pod

### ISSUE THREAD

**Issue by abhilashdk2016** [ehough/docker-nfs-server#68]
Hi sir,

Thank you for this wonderful project.

I was able to start the server in Ubuntu 20.04.

<img width="1680" alt="Screenshot 2021-08-01 at 12 50 47 PM" src="https://user-images.githubusercontent.com/16358319/127762779-fcc7c724-8ba8-4d41-a66d-7accefefb81e.png">

Now I am trying to use this nfs server as volume mount using the below yaml definition:
`
```
apiVersion: apps/v1

kind: Deployment
metadata:
  labels:
    app: busybox
  name: busybox
 spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - image: busybox
        name: busybox
        command: ["/bin/sh"]
        args: ["-c","echo 'At Work!' >> /mnt/log.txt; while true; do date >> /mnt/log.txt; sleep 10; done;"]
        volumeMounts:
          - name: nfs
            mountPath: "/mnt"
      volumes:
      - name: nfs
        nfs:
          server: nfs-server
          path: /
````

But nfs is not being mounted and I am getting the following error:
<img width="1680" alt="Screenshot 2021-08-01 at 12 57 40 PM" src="https://user-images.githubusercontent.com/16358319/127762979-35d7f380-2e3b-4728-843c-c35b4a5baea0.png">

Could you please help me in understanding how to mount a volume based of your nfs-server.

Thanks in advance.
