### ISSUE TITLE
ERROR: unable to mount rpc_pipefs filesystem onto /var/lib/nfs/rpc_pipefs

### ISSUE THREAD

**Issue by a-camacho** [ehough/docker-nfs-server#90]
Hi guys,

Have been trying to deploy this container in a Docker Swarm on a Debian machine.
Impossible for me to get throught this error :

**docker-compose.yml**

```
  nfs:
    image: erichough/nfs-server
    volumes:
      - my_docker_volume_used_by_another_container:/nfs
      - /lib/modules:/lib/modules:ro
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_MODULE
    #ports:
      #- 2049:2049
      #- 111:111
      #- 32767:32767
      #- 32765:32765
    network_mode: host
    security_opt:
      - apparmor=erichough-nfs
    environment:
      - "NFS_LOG_LEVEL=DEBUG"
      - "NFS_VERSION=3"
      - "NFS_EXPORT_0=/nfs                  *(rw,fsid=0,insecure,no_subtree_check,sync)"
```

I tried :

- Using `network_mode=host`
- Disabling AppArmor (but also creating and activating AppArmor profile as in docs)
- Using `privileged: true`

Here are my error logs (level=debug)

```
==================================================================
      SETTING UP ...
==================================================================
----> log level set to DEBUG
----> will use 4 rpc.nfsd server thread(s) (1 thread per CPU)
----> building /etc/exports from environment variables
----> collected 1 valid export(s) from NFS_EXPORT_* environment variables
----> kernel module nfs is loaded
----> kernel module nfsd is loaded
----> setup complete
==================================================================
      STARTING SERVICES ...
==================================================================
----> mounting rpc_pipefs filesystem onto /var/lib/nfs/rpc_pipefs
mount: mount('rpc_pipefs','/var/lib/nfs/rpc_pipefs','rpc_pipefs',0x00008000,'(null)'):-1: Permission denied
mount: mount('rpc_pipefs','/var/lib/nfs/rpc_pipefs','rpc_pipefs',0x00008001,'(null)'):-1: Permission denied
mount: mounting rpc_pipefs on /var/lib/nfs/rpc_pipefs failed: Permission denied
----> 
----> ERROR: unable to mount rpc_pipefs filesystem onto /var/lib/nfs/rpc_pipefs
----> 
==================================================================
      TERMINATING ...
==================================================================
----> terminating nfsd
----> WARNING: unable to terminate nfsd. if it had started already, check Docker host for lingering [nfsd] processes
----> rpc.statd was not running
----> rpc.mountd was not running
----> un-exporting filesystem(s)
----> rpcbind was not running
----> no active mount at /proc/fs/nfsd
----> no active mount at /var/lib/nfs/rpc_pipefs
==================================================================
      TERMINATED
==================================================================
```

**Comment by Luis97lol** [comment]
I'm facing the same issue

**Comment by lucasandre22** [comment]
Same issue here. The solution I had was to use another container:


```
version: "3.8"

services:
  nfs-server:
    image: itsthenetwork/nfs-server-alpine:latest
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    ports:
      - "2049:2049"
    environment:
      SHARED_DIRECTORY: "/nfs"
    volumes:
      - ./db:/nfs # NFS path to share
      - /lib/modules:/lib/modules:ro
    cap_add:
      - SYS_ADMIN
      - SYS_MODULE
    deploy:
      placement:
        constraints:
          - "node.role == manager"
```
