### ISSUE TITLE
/usr/local/bin/entrypoint.sh Killed

### ISSUE THREAD

**Issue by cjvirtucio87** [ehough/docker-nfs-server#94]
Hi, I'm trying to run version `2.2.1` of the container image. The process keeps getting killed at [this line](https://github.com/ehough/docker-nfs-server/blob/v2.2.1/entrypoint.sh#L878) and I'm not sure why.

```console
      READY AND WAITING FOR NFS CLIENT CONNECTIONS
==================================================================
rpc.statd: Version 2.3.4 starting
rpc.statd: Flags: No-Daemon Log-STDERR TI-RPC
rpc.statd: Failed to read /var/lib/nfs/state: Address in use
rpc.statd: Initializing NSM state
rpc.statd: Local NSM state number: 3
rpc.statd: Failed to open /proc/sys/fs/nfs/nsm_local_state: Read-only file system




/usr/local/bin/entrypoint.sh: line 878:    41 Killed                  "$process" "${process_args[@]}"
```

Not entirely sure where to look to investigate further.

Command:

```console
#!/usr/bin/env bash

DOCKER_NFS_SERVER_URI='dkr-registry.home.cjvirtuc.io/docker-hub-proxy/erichough/nfs-server@sha256:1efd4ece380c5ba27479417585224ef857006daa46ab84560a28c1224bc71e9e'


docker run \
  --detach \
  --name nfs \
  --env NFS_LOG_LEVEL=DEBUG \
  --cap-add=SYS_ADMIN \
  --cap-add=SYS_MODULE \
  --publish 2049:2049 \
  --mount 'type=bind,src=/srv/nfs-ssd,dst=/srv/nfs-ssd' \
  --mount "type=bind,src=/etc/docker-nfs-server/exports,dst=/etc/exports,ro" \
  --mount "type=bind,src=/lib/modules,dst=/lib/modules,ro" \
  "${DOCKER_NFS_SERVER_URI}"
```

Not sure if it's related but here's my exports file. Pretty straightforward:

```txt
/srv/nfs-ssd/exports 10.101.1.31/24(ro,no_subtree_check,fsid=0)
/srv/nfs-ssd/exports/dev/data-plane 10.101.1.31/24(rw,sync,no_subtree_check,no_root_squash)
```

**Comment by agibson-fl** [comment]
This container was working for me when my host was running Debian 12.  Right after I upgraded my host to Debian 13, I'm getting the exact same problem posted here.

Here's my docker-compose.yml file:

```
  GNU nano 8.4                                                                                 docker-compose.yml                                                                                           
services:
  nfs-server:
    image: erichough/nfs-server
    container_name: nfs-server
    restart: always
    volumes:
     [redacted path mounts]
      - ./exports:/etc/exports:ro
      - /lib/modules:/lib/modules:ro
    privileged: true
    environment:
      - NFS_VERSION=3
      - NFS_LOG_LEVEL=DEBUG
    cap_add:
      # this doesn't work, but privileged mode does.
      #- SYS_ADMIN
      - SYS_MODULE
    networks:
      - nfs_network
    # Can't get nfsv4 working, so we need all these binds to work properly.
    ports:
      - 2049:2049
      - 2049:2049/udp
      - 111:111
      - 111:111/udp
      - 32765:32765
      - 32765:32765/udp
      - 32767:32767
      - 32767:32767/udp

networks:
  nfs_network:
    name: nfs_network
    driver: bridge
```
